name = "ChairmarksForAirspeedVelocity"
uuid = "03f6ca6c-aa78-4850-b881-17e0d6a7eae9"
authors = ["Lilith Orion Hafner <lilithhafner@gmail.com> and contributors"]
version = "1.0.0"

[deps]
BenchmarkTools = "6e4b80f9-dd63-53aa-95a3-0cdb28fa8baf"
Chairmarks = "0ca39b1e-fe0b-4e98-acfc-b1656634c4de"

[compat]
BenchmarkTools = "1.6.0"
Chairmarks = "1.3.1"
julia = "1.6.7"

[extras]
Aqua = "4c88cf16-eb10-579e-8560-4a9242c79595"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Aqua", "Test"]
