name: CI
on:
  push:
    branches:
      - main
    tags: ['*']
  pull_request:
jobs:
  quick-test:
    name: Julia 1 - ubuntu-latest - x64 - ${{ github.event_name }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: julia-actions/setup-julia@v2
        with:
          version: 1
          arch: x64
      - uses: julia-actions/julia-runtest@v1
      # Skip coverage on the quick test to save serial time.
      # If something is only covered here and nowhere else, it's not adequately covered.
  test:
    name: Julia ${{ matrix.julia-version }} - ${{ matrix.os }} - ${{ matrix.julia-arch }} - ${{ github.event_name }}
    needs: quick-test
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
            julia-arch: x64
            julia-version: nightly
          - os: ubuntu-latest
            julia-arch: x64
            julia-version: pre
          - os: ubuntu-latest
            julia-arch: x64
            julia-version: lts
          - os: ubuntu-latest
            julia-arch: x64
            julia-version: min

          - os: ubuntu-latest
            julia-arch: x86
            julia-version: 1
          - os: macOS-latest
            julia-arch: aarch64
            julia-version: 1
          - os: macOS-latest
            julia-arch: x64
            julia-version: 1
          - os: windows-latest
            julia-arch: x64
            julia-version: 1
          - os: windows-latest
            julia-arch: x86
            julia-version: 1

          - os: ubuntu-latest
            julia-arch: x86
            julia-version: nightly
          - os: ubuntu-latest
            julia-arch: x86
            julia-version: min

          - os: macOS-latest
            julia-arch: aarch64
            julia-version: lts
          - os: macOS-latest
            julia-arch: aarch64
            julia-version: pre
          - os: windows-latest
            julia-arch: x64
            julia-version: lts
          - os: windows-latest
            julia-arch: x64
            julia-version: pre
    steps:
      - uses: actions/checkout@v4
      - uses: julia-actions/setup-julia@v2
        with:
          version: ${{ matrix.julia-version }}
          arch: ${{ matrix.julia-arch }}
      - uses: julia-actions/julia-runtest@v1
      - uses: julia-actions/julia-processcoverage@v1
        if: ${{ matrix.julia-version == 'min' && matrix.julia-arch == 'x64' || matrix.julia-version == 1 && matrix.os == 'ubuntu-latest' }}
      - uses: codecov/codecov-action@v5
        # Only upload two runs. We should cover everything in one of these two cases.
        if: ${{ matrix.julia-version == 'min' && matrix.julia-arch == 'x64' || matrix.julia-version == 1 && matrix.os == 'ubuntu-latest' }}
        with:
          files: lcov.info
  typos:
    name: Typos
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: crate-ci/typos@master
